[package]
name = "heystack"
version = "0.1.0"
authors = ["曹鉴恩 <caojen@mail2.sysu.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
